export default [
  "Chat names to ID",
  {
    type: "text",
    data: {
      labels: [
        "the quiet council",
        "daily photo friends!!",
        "Zelda! >:D",
        "Zarin Birthday",
        "Writers, Chroniclers, Storytellers, and Wayfarers",
        "Utah peeps!",
        "To The Moon Tour 2023",
        "The Council Party Room",
        "TABC and Release 2022",
        "Surprise party for Ari",
        "Spiderman",
        "Polish Your Armor",
        "Personal Finance",
        "Loosli Family",
        "Lil Rant Zone",
        "July 24th Provo Meetup",
        "Hehehehehehehehe",
        "Fun Medical Stories",
        "Family Haven Website",
        "Dracula Book Club",
        "DM with Zarin Loosli/Zarin Loosli-School",
        "DM with Zarin Loosli/Victor Loosli",
        "DM with Zarin Loosli/Taska Chrisman",
        "DM with Zarin Loosli/Shion “Shiacookie” Cook",
        "DM with Zarin Loosli/Shalin Hale (shay)",
        "DM with Zarin Loosli/Shalin Hale",
        "DM with Zarin Loosli/Sasha Hanson",
        "DM with Zarin Loosli/Sasha Hanson",
        "DM with Zarin Loosli/Nutella is Life/Kyle Loosli/Melissa Loosli",
        "DM with Zarin Loosli/Nutella is Life/Analee Loosli",
        "DM with Zarin Loosli/Nutella is Life",
        "DM with Zarin Loosli/Norah Milner/Ariana Harrison/Amanda K. G. Hemmert",
        "DM with Zarin Loosli/Norah Milner",
        "DM with Zarin Loosli/Nancy Heart",
        "DM with Zarin Loosli/Merlin Blanchard",
        "DM with Zarin Loosli/Melissa Loosli",
        "DM with Zarin Loosli/Loosli Family",
        "DM with Zarin Loosli/Kyle Loosli/Melissa Loosli",
        "DM with Zarin Loosli/Kyle Loosli",
        "DM with Zarin Loosli/Kiara Harrison",
        "DM with Zarin Loosli/Kelly L. Clark/Shalin Hale (shay)/Amanda K. G. Hemmert",
        "DM with Zarin Loosli/Kelly L. Clark",
        "DM with Zarin Loosli/Kalthewiz",
        "DM with Zarin Loosli/Joshua Taylor",
        "DM with Zarin Loosli/Jody McOmber",
        "DM with Zarin Loosli/JaymeLee Womack/Caitlynn Hendricks (Kit-Kat)/Shalin Hale (shay)/Ariana Harrison",
        "DM with Zarin Loosli/JaymeLee Womack/Ariana Harrison/Nancy Heart",
        "DM with Zarin Loosli/JaymeLee Womack/Ariana Harrison/Anna Bell/Kalthewiz/Amanda K. G. Hemmert",
        "DM with Zarin Loosli/JaymeLee Womack",
        "DM with Zarin Loosli/Janelle Christensen",
        "DM with Zarin Loosli/Fruity Pebbles",
        "DM with Zarin Loosli/Emmalee Christensen",
        "DM with Zarin Loosli/Emily Carlisle",
        "DM with Zarin Loosli/Eliza Williamson",
        "DM with Zarin Loosli/EN Loosli",
        "DM with Zarin Loosli/Diérdre Maness",
        "DM with Zarin Loosli/Diérdre Maness",
        "DM with Zarin Loosli/Daria Loosli",
        "DM with Zarin Loosli/Caitlynn Hendricks (Kit-Kat)/Ariana Harrison/Anna Bell",
        "DM with Zarin Loosli/Caitlynn Hendricks (Kit-Kat)/Ariana Harrison",
        "DM with Zarin Loosli/Caitlynn Hendricks (Kit-Kat)",
        "DM with Zarin Loosli/Ariana Harrison/Sasha Hanson/Anna Bell/Kalthewiz/Shayne Hayes/Amanda K. G. Hemmert",
        "DM with Zarin Loosli/Ariana Harrison/Anna Bell/Amanda K. G. Hemmert",
        "DM with Zarin Loosli/Ariana Harrison/Anna Bell",
        "DM with Zarin Loosli/Ariana Harrison/Anna Bell",
        "DM with Zarin Loosli/Ariana Harrison/Amanda K. G. Hemmert",
        "DM with Zarin Loosli/Ariana Harrison/Amanda K. G. Hemmert",
        "DM with Zarin Loosli/Ariana Harrison",
        "DM with Zarin Loosli/Anna Bell",
        "DM with Zarin Loosli/Analee Loosli",
        "DM with Zarin Loosli/Amanda K. G. Hemmert",
        "DM with Zarin Loosli/Alyssa Meldrum",
        "DM with Zarin Loosli/Ada Scott/Caitlynn Hendricks (Kit-Kat)/Ariana Harrison/Joshua Taylor/Amanda K. G. Hemmert/Sage Pratt",
        "DM with Zarin Loosli/Ada Scott",
        "DM with Zarin Loosli",
        "DM with Zarin Loosli",
        "DM with Zarin Loosli",
        "DM with Zarin Loosli",
        "DM with Zarin Loosli",
        "DM with Zarin Loosli",
        "DM with Zarin Loosli",
        "DM with Suzannah Maness/Zarin Loosli",
        "DM with Olivia Maloy/Zarin Loosli",
        "DM with Mariah Sparrow/Zarin Loosli",
        "DM with Lenicka Lee/Zarin Loosli",
        "DM with Jennie Monasmith/Zarin Loosli",
        "DM with Dallin Loosli/Zarin Loosli/Nutella is Life/Fruity Pebbles/Analee Loosli/Daria Loosli",
        "DM with Dallin Loosli/Zarin Loosli",
        "DM with Aélis/Zarin Loosli",
        "Council Sorority And Graduates",
        "Council Retreat",
        "Cornerhouse Maintenance",
        "Computer shopping",
        "CTOW Sorority (And Interested Parties)",
        "CTOW Realms of Conflict",
      ],
      datasets: [
        {
          data: [
            "Space AAAAmdi4YTY",
            "Space AAAAg8KI6ac",
            "Space AAAAsrmsgWI",
            "Space AAQA2m-3eC4",
            "Space AAAAFCjArrQ",
            "Space AAAAvMjIr5Q",
            "Space AAAAtuD0nsM",
            "Space AAAA3JuPmKg",
            "Space AAAAQREVhps",
            "Space AAAAiManlJs",
            "Space AAAAHw8RqgM",
            "Space AAAAAn3Gus0",
            "Space AAAArTlB4Q4",
            "Space AAAAkQdPHPc",
            "Space AAAAjBOdkzY",
            "Space AAAA66uSLhY",
            "Space AAAAoZ5cK84",
            "Space AAAA-j1i1Uc",
            "Space AAAAiWkpXfg",
            "Space AAAAWrT_FwE",
            "DM -27RnQAAAAE",
            "DM phWg-wAAAAE",
            "DM hgt6-MAAAAE",
            "DM pRLDyQAAAAE",
            "DM vVJF2QAAAAE",
            "DM 3-Rp2QAAAAE",
            "DM -QAvHQAAAAE",
            "Space AAAAoTQbOW4",
            "Space AAAAjR9h064",
            "Space AAAAmbl1Ln8",
            "DM 0GtWSQAAAAE",
            "Space AAAADXGuyos",
            "DM 2CsSCQAAAAE",
            "DM wFZUWEAAAAE",
            "DM 2yxqOQAAAAE",
            "DM rqeOSQAAAAE",
            "DM giYLmwAAAAE",
            "Space AAAAo9Z2c10",
            "DM sVFvSQAAAAE",
            "DM i8FB0EAAAAE",
            "Space AAQAGqREw14",
            "DM je0JDQAAAAE",
            "DM _QphyQAAAAE",
            "DM 2jfTQIAAAAE",
            "DM s12tIiAAAAE",
            "Space AAAA7UboWkc",
            "Space AAAAcwrbB9c",
            "Space AAAAF4tuuxI",
            "DM mtM-swAAAAE",
            "DM imKdqIAAAAE",
            "DM wBl9fsAAAAE",
            "DM _Gm9zQAAAAE",
            "DM kt_CCQAAAAE",
            "DM rP51TwAAAAE",
            "DM jvTCm4AAAAE",
            "DM juN07kAAAAE",
            "DM zk_lxwAAAAE",
            "DM sM-lOwAAAAE",
            "Space AAAA_Z39BUA",
            "Space AAAALXdTO78",
            "DM 2tv57QAAAAE",
            "Space AAAAoq-cnwI",
            "Space AAAAjCRSxmY",
            "Space AAAAl878ND0",
            "Space AAAA9jBV4Es",
            "Space AAAA67P1VBw",
            "Space AAAAlrEjF28",
            "DM 8OlNGQAAAAE",
            "DM oU3SCQAAAAE",
            "DM 0dhdyQAAAAE",
            "DM i-Bq2QAAAAE",
            "DM 6cFlQEAAAAE",
            "Space AAAAnLA7elA",
            "DM 8h0hyQAAAAE",
            "DM 8q8lwUAAAAE",
            "DM pCbcawAAAAE",
            "DM w0oyCQAAAAE",
            "DM 7mDwSQAAAAE",
            "DM vLodfsAAAAE",
            "DM g97mNYAAAAE",
            "DM 90UdzQAAAAE",
            "DM wrk2yQAAAAE",
            "DM iaDnewAAAAE",
            "DM 71NfJwAAAAE",
            "DM rfAqfQAAAAE",
            "DM 25PeAIAAAAE",
            "Space AAQARPZ-xIc",
            "DM 6tPlLQAAAAE",
            "DM tYMKCQAAAAE",
            "Space AAQA_ajOmFk",
            "Space AAAAm7fyc8s",
            "Space AAAAc23Htg8",
            "Space AAAAduI95k0",
            "Space AAAAC7j8n1I",
            "Space AAAAgDFNgTM",
          ],
        },
      ],
    },
  },
  "Message count by year",
  {
    type: "line",
    data: {
      labels: [
        "2015",
        "2016",
        "2017",
        "2018",
        "2019",
        "2020",
        "2021",
        "2022",
        "2023",
        "2024",
        "2025",
        "2026",
      ],
      datasets: [
        {
          data: [
            380, 5865, 5215, 4667, 4058, 25001, 17896, 8805, 4583, 3724, 6523,
            683,
          ],
          borderColor: "rgb(54, 162, 235)",
          backgroundColor: "rgba(54, 162, 235, 0.5)",
        },
      ],
    },
    options: {
      plugins: {},
      scales: {
        x: {
          axis: "x",
          type: "category",
          ticks: {
            minRotation: 0,
            maxRotation: 50,
            mirror: false,
            textStrokeWidth: 0,
            textStrokeColor: "",
            padding: 3,
            display: true,
            autoSkip: true,
            autoSkipPadding: 3,
            labelOffset: 0,
            minor: {},
            major: {},
            align: "center",
            crossAlign: "near",
            showLabelBackdrop: false,
            backdropColor: "rgba(255, 255, 255, 0.75)",
            backdropPadding: 2,
            color: "#666",
          },
          display: true,
          offset: false,
          reverse: false,
          beginAtZero: false,
          bounds: "ticks",
          clip: true,
          grace: 0,
          grid: {
            display: true,
            lineWidth: 1,
            drawOnChartArea: true,
            drawTicks: true,
            tickLength: 8,
            offset: false,
            color: "rgba(0,0,0,0.1)",
          },
          border: {
            display: true,
            dash: [],
            dashOffset: 0,
            width: 1,
            color: "rgba(0,0,0,0.1)",
          },
          title: {
            display: false,
            text: "",
            padding: {
              top: 4,
              bottom: 4,
            },
            color: "#666",
          },
          id: "x",
          position: "bottom",
        },
        y: {
          axis: "y",
          type: "linear",
          ticks: {
            minRotation: 0,
            maxRotation: 50,
            mirror: false,
            textStrokeWidth: 0,
            textStrokeColor: "",
            padding: 3,
            display: true,
            autoSkip: true,
            autoSkipPadding: 3,
            labelOffset: 0,
            minor: {},
            major: {},
            align: "center",
            crossAlign: "near",
            showLabelBackdrop: false,
            backdropColor: "rgba(255, 255, 255, 0.75)",
            backdropPadding: 2,
            color: "#666",
          },
          display: true,
          offset: false,
          reverse: false,
          beginAtZero: false,
          bounds: "ticks",
          clip: true,
          grace: 0,
          grid: {
            display: true,
            lineWidth: 1,
            drawOnChartArea: true,
            drawTicks: true,
            tickLength: 8,
            offset: false,
            color: "rgba(0,0,0,0.1)",
          },
          border: {
            display: true,
            dash: [],
            dashOffset: 0,
            width: 1,
            color: "rgba(0,0,0,0.1)",
          },
          title: {
            display: false,
            text: "",
            padding: {
              top: 4,
              bottom: 4,
            },
            color: "#666",
          },
          id: "y",
          position: "left",
        },
      },
    },
  },
  "Message count by month",
  {
    type: "line",
    data: {
      labels: [
        "November 2015",
        "December 2015",
        "January 2016",
        "February 2016",
        "March 2016",
        "April 2016",
        "May 2016",
        "June 2016",
        "July 2016",
        "August 2016",
        "September 2016",
        "October 2016",
        "November 2016",
        "December 2016",
        "January 2017",
        "February 2017",
        "March 2017",
        "April 2017",
        "May 2017",
        "June 2017",
        "July 2017",
        "August 2017",
        "September 2017",
        "October 2017",
        "November 2017",
        "December 2017",
        "January 2018",
        "February 2018",
        "March 2018",
        "April 2018",
        "May 2018",
        "June 2018",
        "July 2018",
        "August 2018",
        "September 2018",
        "October 2018",
        "November 2018",
        "December 2018",
        "January 2019",
        "February 2019",
        "March 2019",
        "April 2019",
        "May 2019",
        "June 2019",
        "July 2019",
        "August 2019",
        "September 2019",
        "October 2019",
        "November 2019",
        "December 2019",
        "January 2020",
        "February 2020",
        "March 2020",
        "April 2020",
        "May 2020",
        "June 2020",
        "July 2020",
        "August 2020",
        "September 2020",
        "October 2020",
        "November 2020",
        "December 2020",
        "January 2021",
        "February 2021",
        "March 2021",
        "April 2021",
        "May 2021",
        "June 2021",
        "July 2021",
        "August 2021",
        "September 2021",
        "October 2021",
        "November 2021",
        "December 2021",
        "January 2022",
        "February 2022",
        "March 2022",
        "April 2022",
        "May 2022",
        "June 2022",
        "July 2022",
        "August 2022",
        "September 2022",
        "October 2022",
        "November 2022",
        "December 2022",
        "January 2023",
        "February 2023",
        "March 2023",
        "April 2023",
        "May 2023",
        "June 2023",
        "July 2023",
        "August 2023",
        "September 2023",
        "October 2023",
        "November 2023",
        "December 2023",
        "January 2024",
        "February 2024",
        "March 2024",
        "April 2024",
        "May 2024",
        "June 2024",
        "July 2024",
        "August 2024",
        "September 2024",
        "October 2024",
        "November 2024",
        "December 2024",
        "January 2025",
        "February 2025",
        "March 2025",
        "April 2025",
        "May 2025",
        "June 2025",
        "July 2025",
        "August 2025",
        "September 2025",
        "October 2025",
        "November 2025",
        "December 2025",
        "January 2026",
        "February 2026",
        "March 2026",
      ],
      datasets: [
        {
          data: [
            53, 327, 323, 467, 514, 461, 211, 395, 324, 550, 659, 434, 633, 894,
            505, 496, 484, 542, 521, 434, 441, 348, 323, 324, 324, 473, 486,
            341, 443, 410, 299, 417, 512, 510, 294, 281, 327, 347, 246, 382,
            474, 300, 301, 364, 387, 323, 271, 356, 244, 410, 192, 206, 444,
            4120, 3069, 1778, 750, 1058, 516, 4259, 5552, 3057, 3479, 3278,
            1379, 822, 593, 780, 1985, 1119, 910, 924, 967, 1660, 495, 387,
            1073, 548, 374, 383, 294, 806, 1737, 980, 1249, 479, 265, 277, 529,
            418, 418, 286, 414, 595, 551, 450, 180, 200, 527, 620, 721, 279, 96,
            96, 170, 170, 113, 385, 306, 241, 594, 445, 781, 411, 398, 543, 873,
            632, 750, 247, 433, 416, 263, 372, 48,
          ],
        },
      ],
    },
  },
];
